import { useEffect, useState } from "react";
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { signOut } from "firebase/auth";
import { auth } from "../firebase-config";
import HomePage from "@/component/home/homepage";
import Link from 'next/link';
import { BsGithub, BsTwitter, BsLinkedin } from 'react-icons/bs';


export default function Home() {

  return (
    <>
      <Head>
        <title>Alx blog-posts portfolio project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/png.png" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.center}>Blog Forum</h1>
        <div className={styles.home__links}>
          <Link href="/" ><BsGithub className={styles.icon__link} /></Link>
          <Link href="/" ><BsTwitter className={styles.icon__link} /> </Link>
          <Link href="/" ><BsLinkedin className={styles.icon__link} /></Link>
        </div>
        <div>
          <Link href="/sign/login">View Blogs</Link>
        </div>
      </main>

    </>
  )
}
